### ISSUE TITLE
Very helpful information 

### ISSUE THREAD

**Issue by Khairunj** [MicrosoftDocs/intelligent-asset-manager#7]
I found the information very helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f76559d-236e-19c7-e93f-dd21c6fc737f
* Version Independent ID: cecf609f-bd41-7088-7273-f0e0eae4865a
* Content: [Tutorial SAM Engagement Managers - Intelligent Asset Manager](https://docs.microsoft.com/en-us/intelligent-asset-manager/tutorials/sam-ems/tutorial)
* Content Source: [Intelligent-asset/Tutorials/SAM-EMs/Tutorial.md](https://github.com/MicrosoftDocs/intelligent-asset-manager/blob/live/Intelligent-asset/Tutorials/SAM-EMs/Tutorial.md)
* Product: **intelligent-asset-mgr**
* GitHub Login: @BeatrizCampos-IAM
* Microsoft Alias: **v-beaca**

**Comment by filipgoris** [comment]
Thank you for your feedback.
